### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by 4d62ext** [henrywhitaker3/adguard-exporter#11]
Hello @henrywhitaker3, I've observed that AdGuard Exporter consumes approximately 5 times more memory compared to AdGuard itself. Could there be a feature I'm overlooking, or might there be a bug within the program?

![](https://cdn.4d62.me/u/brave_C6oX45uETJ.png)

Given that the exporter monitors a single container focusing on fewer tasks compared to my other monitoring containers (which consume in total less than 200MB), it logically should consume less memory.

Thanks

edit: i just noticed how much typos and mistakes i made in the original message lol. deleted old versions for my sake

**Comment by henrywhitaker3** [comment]
Hmm, that's weird. Where are you running this?

Mine shows very minimal usage for my 2 instances:

```
CONTAINER ID   NAME               CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O        PIDS
9024515e3565   henry-exporter-1   0.00%     10.77MiB / 454.2MiB   2.37%     147MB / 683MB   65.2MB / 0B      7
774933c304f9   henry-adguard-1    0.01%     58.75MiB / 454.2MiB   12.94%    0B / 0B         289MB / 6.07MB   7
```

```
CONTAINER ID   NAME               CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O        PIDS
bae56386aa60   henry-exporter-1   0.06%     9.898MiB / 454.2MiB   2.18%     119MB / 401MB   58.6MB / 0B      7
7b144a986bc0   henry-adguard-1    0.00%     59.05MiB / 454.2MiB   13.00%    0B / 0B         220MB / 4.03MB   7
```

**Comment by henrywhitaker3** [comment]
Seeing as that's running in grafana, do you have a graph of usage over time?

**Comment by henrywhitaker3** [comment]
Have just pushed a new version out, could you run it with the env var `DEBUG` set to `true` please mate, then let me know when the memory usage spikes again. Then we can pull a profile from to figure out where the leak is

**Comment by henrywhitaker3** [comment]
Weird, the newer version shouldn't have changed anything. Open this back up if it happens again
