### ISSUE TITLE
Upgrade to Grafana Flux

### ISSUE THREAD

**Issue by CrazyWolf13** [henrywhitaker3/adguard-exporter#16]
Hi as Grafana is more and more forcing users to use Flux language I'd really love to see a flux version basically the same as https://github.com/eko/pihole-exporter did.

Adguard Exporter includes a prometheus instanced, exposes metrics, telegraf instance (docker container) queries data from prometheus adguardexporter and stores them in influxdb where grafana is fetching them from.

But when using Influxdb 2.x one has to use flux language, so I cannot import this dashboard, so I'm really hoping for a flux version as here:

https://grafana.com/grafana/dashboards/17094-pi-hole-exporter-influxdb-2/

**Comment by henrywhitaker3** [comment]
Hi mate, I don't use influx/know flux so won't be doing this - happy to accept a PR for it though
