### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by 4d62ext** [henrywhitaker3/adguard-exporter#17]
I seem to be getting this error: `exec /adguard-exporter: exec format error` when pulling and running the image in Portainer? Started happening today. Is there a way to fix the issue? I tried recreating the container, the stack, re-pulling the image, and more.

**Comment by henrywhitaker3** [comment]
What are you running this on? Go exec errors generally happen when it's trying to run on a system it wasn't built for (docker image is linux amd64)

**Comment by henrywhitaker3** [comment]
I haven't got round to building one for arm yet #9

If you clone and build `local.Dockerfile` then it should work
