### ISSUE TITLE
Can't grab stats using Let's Encrypt SSL Certs

### ISSUE THREAD

**Issue by jarjarfinks** [henrywhitaker3/adguard-exporter#22]
`ERROR - could not get dhcp status: Get "https://adguard.jfinks.com/control/dhcp/status": tls: failed to verify certificate: x509: certificate signed by unknown authority`

This and many errors for other URLs with the same complaint are popping up. Any way to skip SSL cert validation?

**Comment by henrywhitaker3** [comment]
Hey @jarjarfinks pleae try the latest version

**Comment by jarjarfinks** [comment]
That works! Thanks!
