### ISSUE TITLE
Make binaries available as part of releases [Feature]

### ISSUE THREAD

**Issue by brianramseyau** [henrywhitaker3/adguard-exporter#34]
Thanks for the exporter, super useful now the old alternative was deleted!

Would be great if you could add pre-built binaries for all the supported archs to the Github Releases, making it easier to grab them directly instead of having to grab the source and compile.

**Comment by brianramseyau** [comment]
@4d62 feels a little rich to call an open source mostly set and forget project "unmaintained" after only a few months of no commits, I have more faith than that, life happens :)

**Comment by henrywhitaker3** [comment]
Yeah, not much activity on this as there's not a huge amount to do really without any bug reports. Not sure why goreleaser didn't upload the binaries to the last release properly, but the latest release has them uploaded
