### ISSUE TITLE
Missing SERVER_PORT env

### ISSUE THREAD

**Issue by jordanlambrecht** [henrywhitaker3/adguard-exporter#7]
There's no SERVER_PORT env variable, so I'm not sure how to direct it correctly except for including it in the ADGUARD_SERVERS section as 192.168.1.2:8080

**Comment by henrywhitaker3** [comment]
Yeah, that should just work in the `ADGUARD_SERVERS` part

**Comment by jordanlambrecht** [comment]
Also getting an error for not having a `ADGUARD_PROTOCOL` variable

**Comment by henrywhitaker3** [comment]
You need the scheme in the url, which I've just noticed the readme doesn't show, will update it now

**Comment by jordanlambrecht** [comment]
Great, thanks man. Glad someone is reviving this project.

**Comment by henrywhitaker3** [comment]
No worries, I added an example relabling in the readme too if you want to strip out the `http` and port when it gets scraped
