### ISSUE TITLE
Dial TCP I/o Timeout

### ISSUE THREAD

**Issue by jordanlambrecht** [henrywhitaker3/adguard-exporter#8]
Currently getting this error:

```
ERROR - could not get stats: Get "http://192.168.1.22/control/stats": dial tcp 192.168.1.22:80: i/o timeout
ERROR - could not get status: Get "http://192.168.1.22/control/status": dial tcp 192.168.1.22:80: i/o timeout
ERROR - could not get query type stats: Get "http://192.168.1.22/control/querylog?limit=1000&response_status=all": dial tcp 192.168.1.75:80: i/o timeout
ERROR - could not get dhcp status: Get "http://192.168.1.22/control/dhcp/status": dial tcp 192.168.1.22:80: i/o timeout
```

Any ideas? Originally, I got "forbidden" when I visited the URL via browser until I logged in, so I thought maybe it was a cookie issue or something, but that doesn't seem to be the case

**Comment by henrywhitaker3** [comment]
Can you try running `telnet 192.168.1.22 80` from the host running the exporter?

**Comment by jordanlambrecht** [comment]
Yup, it connects without issue.

**Comment by henrywhitaker3** [comment]
Weird, can you try the latest version and post your docker-compose/however you are running this please?
